In [3]:
import os
import numpy as np
import pandas as pd

from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer, KNNImputer
from sklearn.preprocessing import MinMaxScaler, StandardScaler, OneHotEncoder, LabelBinarizer
from sklearn.model_selection import train_test_split, StratifiedKFold, GridSearchCV
from sklearn.metrics import classification_report, accuracy_score, make_scorer

from sklearn.linear_model import LogisticRegression

from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier


import eli5

pd.set_option('max_columns', None)

In [4]:
def data_preprocess(df):
    return df

In [5]:
def generate_next_submission_fileid():
    files_found = []
    for file in os.listdir("../../data"):
        if file.startswith("water_pump_submission"):
            files_found.append(file[22:24])
    if not files_found:
        return '01'
    return f'{int(sorted(files_found).pop()) + 1 :02}'

In [6]:
def submission_file_error_counts(df):
    a = df['status_group'].value_counts().rename_axis('status_group').reset_index(name='predicted_count')
    a.insert(1,'target_count',[8110,5672,1068])
    a['count_error'] = a['predicted_count'] - a['target_count']
    display(a)

In [7]:
def create_submission_file(pipeline, X_test, filename_comment, print_errors=False):
    next_file_id = generate_next_submission_fileid()
    X_test_processed = data_preprocess(X_test)
    y_pred_values = pipeline.predict(X_test_processed)
    
    ids = X_test['id'].reset_index(drop=True)
    y_pred = pd.DataFrame(data=y_pred_values, columns=["status_group"])
    y_pred.insert(0, 'id', ids)
    
    if print_errors: submission_file_error_counts(y_pred)
    
    filename = f'../../data/water_pump_submission_{next_file_id}_{filename_comment}.csv'
    y_pred.to_csv(filename, index = False)
    
    return y_pred, filename

In [8]:
X_raw = pd.read_csv('../../data/training_set_values.csv')
y_raw = pd.read_csv('../../data/training_set_labels.csv')

In [9]:
X_test_raw = pd.read_csv('../../data/test_set_values.csv')
y_test = pd.read_csv('../../data/SubmissionFormat.csv')

In [10]:
df = X_raw.merge(y_raw, left_on = 'id', right_on = 'id')
df.head()

,id,amount_tsh,date_recorded,funder,gps_height,installer,longitude,latitude,wpt_name,num_private,basin,subvillage,region,region_code,district_code,lga,ward,population,public_meeting,recorded_by,scheme_management,scheme_name,permit,construction_year,extraction_type,extraction_type_group,extraction_type_class,management,management_group,payment,payment_type,water_quality,quality_group,quantity,quantity_group,source,source_type,source_class,waterpoint_type,waterpoint_type_group,status_group
0,69572,6000.0,2011-03-14,Roman,1390,Roman,34.938093,-9.856322,none,0,Lake Nyasa,Mnyusi B,Iringa,11,5,Ludewa,Mundindi,109,True,GeoData Consultants Ltd,VWC,Roman,False,1999,gravity,gravity,gravity,vwc,user-group,pay annually,annually,soft,good,enough,enough,spring,spring,groundwater,communal standpipe,communal standpipe,functional
1,8776,0.0,2013-03-06,Grumeti,1399,GRUMETI,34.698766,-2.147466,Zahanati,0,Lake Victoria,Nyamara,Mara,20,2,Serengeti,Natta,280,NaN,GeoData Consultants Ltd,Other,NaN,True,2010,gravity,gravity,gravity,wug,user-group,never pay,never pay,soft,good,insufficient,insufficient,rainwater harvesting,rainwater harvesting,surface,communal standpipe,communal standpipe,functional
2,34310,25.0,2013-02-25,Lottery Club,686,World vision,37.460664,-3.821329,Kwa Mahundi,0,Pangani,Majengo,Manyara,21,4,Simanjiro,Ngorika,250,True,GeoData Consultants Ltd,VWC,Nyumba ya mungu pipe scheme,True,2009,gravity,gravity,gravity,vwc,user-group,pay per bucket,per bucket,soft,good,enough,enough,dam,dam,surface,communal standpipe multiple,communal standpipe,functional
3,67743,0.0,2013-01-28,Unicef,263,UNICEF,38.486161,-11.155298,Zahanati Ya Nanyumbu,0,Ruvuma / Southern Coast,Mahakamani,Mtwara,90,63,Nanyumbu,Nanyumbu,58,True,GeoData Consultants Ltd,VWC,NaN,True,1986,submersible,submersible,submersible,vwc,user-group,never pay,never pay,soft,good,dry,dry,machine dbh,borehole,groundwater,communal standpipe multiple,communal standpipe,non functional
4,19728,0.0,2011-07-13,Action In A,0,Artisan,31.130847,-1.825359,Shuleni,0,Lake Victoria,Kyanyamisa,Kagera,18,1,Karagwe,Nyakasimbi,0,True,GeoData Consultants Ltd,NaN,NaN,True,0,gravity,gravity,gravity,other,other,never pay,never pay,soft,good,seasonal,seasonal,rainwater harvesting,rainwater harvesting,surface,communal standpipe,communal standpipe,functional

In [11]:
print(df['status_group'].unique())

['functional' 'non functional' 'functional needs repair']

### Common Pipeline Prep

In [12]:
num_cols = X_raw.select_dtypes('number').columns.tolist()
num_cols.pop(0)
num_cols

['amount_tsh',
 'gps_height',
 'longitude',
 'latitude',
 'num_private',
 'region_code',
 'district_code',
 'population',
 'construction_year']

In [13]:
obj_cols = X_raw.select_dtypes('object').columns.tolist()
obj_cols

['date_recorded',
 'funder',
 'installer',
 'wpt_name',
 'basin',
 'subvillage',
 'region',
 'lga',
 'ward',
 'public_meeting',
 'recorded_by',
 'scheme_management',
 'scheme_name',
 'permit',
 'extraction_type',
 'extraction_type_group',
 'extraction_type_class',
 'management',
 'management_group',
 'payment',
 'payment_type',
 'water_quality',
 'quality_group',
 'quantity',
 'quantity_group',
 'source',
 'source_type',
 'source_class',
 'waterpoint_type',
 'waterpoint_type_group']

In [14]:
bool_cols = [col for col in obj_cols if type(X_raw[col][0])==bool]
bool_cols

['public_meeting', 'permit']

In [15]:
cat_cols_raw = [col for col in obj_cols if col not in bool_cols]
cat_cols_raw

['date_recorded',
 'funder',
 'installer',
 'wpt_name',
 'basin',
 'subvillage',
 'region',
 'lga',
 'ward',
 'recorded_by',
 'scheme_management',
 'scheme_name',
 'extraction_type',
 'extraction_type_group',
 'extraction_type_class',
 'management',
 'management_group',
 'payment',
 'payment_type',
 'water_quality',
 'quality_group',
 'quantity',
 'quantity_group',
 'source',
 'source_type',
 'source_class',
 'waterpoint_type',
 'waterpoint_type_group']

In [16]:
# limit categorical columns we use to those with 25 or less unique values
cat_cols = [a for a in obj_cols if len(X_raw[a].unique()) <= 25]
display(cat_cols)

['basin',
 'region',
 'public_meeting',
 'recorded_by',
 'scheme_management',
 'permit',
 'extraction_type',
 'extraction_type_group',
 'extraction_type_class',
 'management',
 'management_group',
 'payment',
 'payment_type',
 'water_quality',
 'quality_group',
 'quantity',
 'quantity_group',
 'source',
 'source_type',
 'source_class',
 'waterpoint_type',
 'waterpoint_type_group']

In [17]:
# Drop cols per feature importance evaluation
drop_list = ['waterpoint_type_group', 
             'extraction_type_group', 'extraction_type_class',
             'source_type', 'source_class',
             'quality_group',
             'quantity_group'
            ]
cat_cols_pipe = [col for col in cat_cols if col not in drop_list]
cat_cols_pipe

['basin',
 'region',
 'public_meeting',
 'recorded_by',
 'scheme_management',
 'permit',
 'extraction_type',
 'management',
 'management_group',
 'payment',
 'payment_type',
 'water_quality',
 'quantity',
 'source',
 'waterpoint_type']

In [94]:
y = df['status_group']
X = df.drop(columns=['status_group'])
X['date_recorded'] = pd.to_datetime(X['date_recorded'])

# for a first effort, we'll convert bool cols to strings and one-hot encode
for col in bool_cols:
    X[col] = X[col].apply(lambda x: 'True' if x==True else ('False' if x==False else 'missing') )
    
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size = 0.20, random_state = 42)

# REMEBER TO UPDATE/REMOVE PARAMS IN MODEL INSTANTIATION

In [96]:
model = RandomForestClassifier(max_depth=4, random_state=42) #AdaBoostClassifier(random_state=42)

In [97]:
num_pipe = Pipeline([('imputer', SimpleImputer(strategy = 'median')),
                     ('scaler', StandardScaler())])

cat_pipe = Pipeline([('imputer', SimpleImputer(strategy = 'constant', fill_value = 'missing')),
                     ('encoder', OneHotEncoder(handle_unknown = 'ignore', sparse = False))])

In [98]:
preprocessor = ColumnTransformer(transformers = [('cat', cat_pipe, cat_cols_pipe),
                                                 ('num', num_pipe, num_cols)],
                                remainder = 'drop')

In [99]:
pipe = Pipeline([('preprocessor', preprocessor),
                 ('model', model)])

In [100]:
pipe.fit(X_train, y_train);

In [101]:
y_pred_values = pipe.predict(X_val)

### Feature Importance Eval

In [25]:
one_hot_cols = pipe.named_steps['preprocessor'].named_transformers_['cat'].named_steps['encoder'].get_feature_names(input_features=cat_cols_pipe)

In [26]:
one_hot_cols

array(['basin_Internal', 'basin_Lake Nyasa', 'basin_Lake Rukwa',
       'basin_Lake Tanganyika', 'basin_Lake Victoria', 'basin_Pangani',
       'basin_Rufiji', 'basin_Ruvuma / Southern Coast',
       'basin_Wami / Ruvu', 'region_Arusha', 'region_Dar es Salaam',
       'region_Dodoma', 'region_Iringa', 'region_Kagera', 'region_Kigoma',
       'region_Kilimanjaro', 'region_Lindi', 'region_Manyara',
       'region_Mara', 'region_Mbeya', 'region_Morogoro', 'region_Mtwara',
       'region_Mwanza', 'region_Pwani', 'region_Rukwa', 'region_Ruvuma',
       'region_Shinyanga', 'region_Singida', 'region_Tabora',
       'region_Tanga', 'public_meeting_False', 'public_meeting_True',
       'public_meeting_missing', 'recorded_by_GeoData Consultants Ltd',
       'scheme_management_Company', 'scheme_management_None',
       'scheme_management_Other', 'scheme_management_Parastatal',
       'scheme_management_Private operator', 'scheme_management_SWC',
       'scheme_management_Trust', 'scheme_management_VWC',
       'scheme_management_WUA', 'scheme_management_WUG',
       'scheme_management_Water Board',
       'scheme_management_Water authority', 'scheme_management_missing',
       'permit_False', 'permit_True', 'permit_missing',
       'extraction_type_afridev', 'extraction_type_cemo',
       'extraction_type_climax', 'extraction_type_gravity',
       'extraction_type_india mark ii', 'extraction_type_india mark iii',
       'extraction_type_ksb', 'extraction_type_mono',
       'extraction_type_nira/tanira', 'extraction_type_other',
       'extraction_type_other - mkulima/shinyanga',
       'extraction_type_other - play pump',
       'extraction_type_other - rope pump',
       'extraction_type_other - swn 81', 'extraction_type_submersible',
       'extraction_type_swn 80', 'extraction_type_walimi',
       'extraction_type_windmill', 'management_company',
       'management_other', 'management_other - school',
       'management_parastatal', 'management_private operator',
       'management_trust', 'management_unknown', 'management_vwc',
       'management_water authority', 'management_water board',
       'management_wua', 'management_wug', 'management_group_commercial',
       'management_group_other', 'management_group_parastatal',
       'management_group_unknown', 'management_group_user-group',
       'payment_never pay', 'payment_other', 'payment_pay annually',
       'payment_pay monthly', 'payment_pay per bucket',
       'payment_pay when scheme fails', 'payment_unknown',
       'payment_type_annually', 'payment_type_monthly',
       'payment_type_never pay', 'payment_type_on failure',
       'payment_type_other', 'payment_type_per bucket',
       'payment_type_unknown', 'water_quality_coloured',
       'water_quality_fluoride', 'water_quality_fluoride abandoned',
       'water_quality_milky', 'water_quality_salty',
       'water_quality_salty abandoned', 'water_quality_soft',
       'water_quality_unknown', 'quantity_dry', 'quantity_enough',
       'quantity_insufficient', 'quantity_seasonal', 'quantity_unknown',
       'source_dam', 'source_hand dtw', 'source_lake',
       'source_machine dbh', 'source_other',
       'source_rainwater harvesting', 'source_river',
       'source_shallow well', 'source_spring', 'source_unknown',
       'waterpoint_type_cattle trough',
       'waterpoint_type_communal standpipe',
       'waterpoint_type_communal standpipe multiple',
       'waterpoint_type_dam', 'waterpoint_type_hand pump',
       'waterpoint_type_improved spring', 'waterpoint_type_other'],
      dtype=object)

In [27]:
all_cols_post_one_hot = num_cols.copy()
all_cols_post_one_hot.extend(one_hot_cols)
len(all_cols_post_one_hot)

138

In [28]:
eli5.explain_weights(pipe.named_steps['model'], top=50, feature_names=all_cols_post_one_hot)

Explanation(estimator='RandomForestClassifier(random_state=42)', description='\nRandom forest feature importances; values are numbers 0 <= x <= 1;\nall values sum to 1.\n', error=None, method='feature importances', is_regression=False, targets=None, feature_importances=FeatureImportances(importances=[FeatureWeight(feature='waterpoint_type_cattle trough', weight=0.14181435372331905, std=0.005737058142770245, value=None), FeatureWeight(feature='waterpoint_type_communal standpipe', weight=0.14075671871947049, std=0.006169527250756508, value=None), FeatureWeight(feature='payment_type_unknown', weight=0.07000094111809405, std=0.032708682578820245, value=None), FeatureWeight(feature='source_unknown', weight=0.0678814895460472, std=0.0041667372060041835, value=None), FeatureWeight(feature='waterpoint_type_other', weight=0.05175671835821812, std=0.005927899611077629, value=None), FeatureWeight(feature='waterpoint_type_improved spring', weight=0.046784450247216905, std=0.0031846366163118976, value=None), FeatureWeight(feature='source_shallow well', weight=0.03055683400847322, std=0.023704446211747485, value=None), FeatureWeight(feature='water_quality_coloured', weight=0.02791782660987384, std=0.013402880164063906, value=None), FeatureWeight(feature='extraction_type_afridev', weight=0.02624696637974255, std=0.021961215141375993, value=None), FeatureWeight(feature='waterpoint_type_hand pump', weight=0.023755622483634897, std=0.002811984413863169, value=None), FeatureWeight(feature='source_spring', weight=0.01969474035430544, std=0.010467559643989531, value=None), FeatureWeight(feature='waterpoint_type_dam', weight=0.015981640993324043, std=0.004316399258530183, value=None), FeatureWeight(feature='water_quality_fluoride', weight=0.014380487789738008, std=0.006448367501380945, value=None), FeatureWeight(feature='source_lake', weight=0.011161221534581663, std=0.005281033821420458, value=None), FeatureWeight(feature='source_machine dbh', weight=0.00929009652109109, std=0.0035135077478731166, value=None), FeatureWeight(feature='source_rainwater harvesting', weight=0.008266145268588187, std=0.006625994641870185, value=None), FeatureWeight(feature='scheme_management_Water Board', weight=0.00808939663031089, std=0.003471459933575915, value=None), FeatureWeight(feature='quantity_unknown', weight=0.008004718495537, std=0.002037583017293573, value=None), FeatureWeight(feature='permit_missing', weight=0.007904505268278609, std=0.0041464739678729375, value=None), FeatureWeight(feature='scheme_management_SWC', weight=0.007396918250634104, std=0.0013461291488533573, value=None), FeatureWeight(feature='water_quality_fluoride abandoned', weight=0.007381396266491122, std=0.006198582378836266, value=None), FeatureWeight(feature='management_water authority', weight=0.0073495912033924105, std=0.005676334708823484, value=None), FeatureWeight(feature='payment_type_other', weight=0.00719644436993894, std=0.00192366898411483, value=None), FeatureWeight(feature='scheme_management_Private operator', weight=0.007092790755412801, std=0.0012800095345291093, value=None), FeatureWeight(feature='payment_never pay', weight=0.00671175137080645, std=0.005174183555363992, value=None), FeatureWeight(feature='extraction_type_walimi', weight=0.006589783698945727, std=0.002390526497784676, value=None), FeatureWeight(feature='quantity_seasonal', weight=0.00648238074502245, std=0.005151835586243842, value=None), FeatureWeight(feature='region_Mwanza', weight=0.006263179712014098, std=0.0016719677368284393, value=None), FeatureWeight(feature='public_meeting_missing', weight=0.006052842518563608, std=0.001493013472696106, value=None), FeatureWeight(feature='water_quality_unknown', weight=0.005961761022547982, std=0.0014802041844406367, value=None), FeatureWeight(feature='payment_type_per bucket', weight=0.00578579058245179, std=0.005598233530867131, value=None), FeatureWeight(feature='region_Mtwara', weight=0.005009034474034375, std=0.0013251249819640893, value=None), FeatureWeight(feature='quantity_insufficient', weight=0.004910438225412501, std=0.0012496395399472933, value=None), FeatureWeight(feature='amount_tsh', weight=0.004344648674908425, std=0.0013047784617580638, value=None), FeatureWeight(feature='quantity_enough', weight=0.004206984007495503, std=0.0022898487361700907, value=None), FeatureWeight(feature='payment_type_never pay', weight=0.004171045185532226, std=0.0009181932173594575, value=None), FeatureWeight(feature='management_group_commercial', weight=0.004112355142692547, std=0.0027666962184247426, value=None), FeatureWeight(feature='basin_Lake Tanganyika', weight=0.004062659738548774, std=0.0046814803278156306, value=None), FeatureWeight(feature='payment_pay per bucket', weight=0.0039449041010626296, std=0.0027202358787942666, value=None), FeatureWeight(feature='extraction_type_india mark iii', weight=0.003906706157770605, std=0.0011024960365610195, value=None), FeatureWeight(feature='permit_True', weight=0.003682563143303575, std=0.0024406692593183835, value=None), FeatureWeight(feature='extraction_type_ksb', weight=0.0036290508096190784, std=0.0008035074093407843, value=None), FeatureWeight(feature='management_group_parastatal', weight=0.003590496565806101, std=0.002535399975995121, value=None), FeatureWeight(feature='payment_pay monthly', weight=0.0032857238945956492, std=0.002353325284159465, value=None), FeatureWeight(feature='management_wug', weight=0.0032702348629396216, std=0.0025662657441977905, value=None), FeatureWeight(feature='management_vwc', weight=0.0032606754779274964, std=0.0011653916666917613, value=None), FeatureWeight(feature='management_group_user-group', weight=0.0032052949791144094, std=0.0022743409257315193, value=None), FeatureWeight(feature='gps_height', weight=0.0031557104974634567, std=0.001879393863091887, value=None), FeatureWeight(feature='num_private', weight=0.003153827078923511, std=0.0010892665420478675, value=None), FeatureWeight(feature='latitude', weight=0.0031412182739468946, std=0.0011513642619470491, value=None)], remaining=88), decision_tree=None, highlight_spaces=None, transition_features=None, image=None)

In [29]:
y_val.unique().tolist()

['non functional', 'functional', 'functional needs repair']

In [102]:
print(classification_report(y_val, y_pred_values, target_names=y_val.unique().tolist()))

                         precision    recall  f1-score   support

         non functional       0.66      0.97      0.78      6457
             functional       0.00      0.00      0.00       851
functional needs repair       0.89      0.46      0.61      4572

               accuracy                           0.70     11880
              macro avg       0.52      0.48      0.46     11880
           weighted avg       0.70      0.70      0.66     11880

/home/cgridley/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

In [103]:
filename_comment = "random_forest_gridsearch1"
y_pred, filename = create_submission_file(pipe, X_test_raw, filename_comment, print_errors=False)

### Grid Search

In [37]:
grid_space = {'RFC' : {'model__n_estimators': [50, 100],
                       'model__max_features': ['auto', 'sqrt'],
                       'model__max_depth': range(3, 5),
                      },
              'ADA' : {'model__n_estimators': [50, 100],
                       'model__learning_rate': [0.01, 0.1],
                       'model__algorithm': ['SAMME', 'SAMME.R'],
                      }
             }

In [38]:
models = {'RFC': RandomForestClassifier(random_state=42), 
          'ADA' : AdaBoostClassifier(random_state=42)
         }

In [39]:
kfold = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

In [40]:
scoring_list = []
for name, model in models.items():
    pipe = Pipeline([('preprocessor', preprocessor),
                 ('model', model)])
    grid_search = GridSearchCV(pipe, grid_space[name], cv=kfold, scoring = 'accuracy',
                              verbose=1, n_jobs=-1)
    grid_search.fit(X, y)
    scoring_list.append(grid_search)

Fitting 5 folds for each of 8 candidates, totalling 40 fits

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done  40 out of  40 | elapsed:   46.5s finished

Fitting 5 folds for each of 8 candidates, totalling 40 fits

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done  40 out of  40 | elapsed:  4.2min finished

In [41]:
for i, model in enumerate(scoring_list):
    print(model.cv_results_)

{'mean_fit_time': array([ 5.04538717,  9.00621519,  5.47494593,  9.59471827,  6.1585506 ,
       11.03781142,  5.80640411,  8.12353415]), 'std_fit_time': array([0.58256767, 0.38829821, 0.27820813, 0.79646434, 0.39786522,
       0.5551546 , 0.50266441, 0.42928859]), 'mean_score_time': array([0.38593922, 0.70284319, 0.3092464 , 0.54406061, 0.38571439,
       0.5184196 , 0.33811431, 0.26391439]), 'std_score_time': array([0.08242089, 0.09322091, 0.03750695, 0.09720492, 0.09296685,
       0.01755488, 0.07445645, 0.05255025]), 'param_model__max_depth': masked_array(data=[3, 3, 3, 3, 4, 4, 4, 4],
             mask=[False, False, False, False, False, False, False, False],
       fill_value='?',
            dtype=object), 'param_model__max_features': masked_array(data=['auto', 'auto', 'sqrt', 'sqrt', 'auto', 'auto', 'sqrt',
                   'sqrt'],
             mask=[False, False, False, False, False, False, False, False],
       fill_value='?',
            dtype=object), 'param_model__n_estimators': masked_array(data=[50, 100, 50, 100, 50, 100, 50, 100],
             mask=[False, False, False, False, False, False, False, False],
       fill_value='?',
            dtype=object), 'params': [{'model__max_depth': 3, 'model__max_features': 'auto', 'model__n_estimators': 50}, {'model__max_depth': 3, 'model__max_features': 'auto', 'model__n_estimators': 100}, {'model__max_depth': 3, 'model__max_features': 'sqrt', 'model__n_estimators': 50}, {'model__max_depth': 3, 'model__max_features': 'sqrt', 'model__n_estimators': 100}, {'model__max_depth': 4, 'model__max_features': 'auto', 'model__n_estimators': 50}, {'model__max_depth': 4, 'model__max_features': 'auto', 'model__n_estimators': 100}, {'model__max_depth': 4, 'model__max_features': 'sqrt', 'model__n_estimators': 50}, {'model__max_depth': 4, 'model__max_features': 'sqrt', 'model__n_estimators': 100}], 'split0_test_score': array([0.69335017, 0.69377104, 0.69335017, 0.69377104, 0.70984848,
       0.71203704, 0.70984848, 0.71203704]), 'split1_test_score': array([0.69840067, 0.69907407, 0.69840067, 0.69907407, 0.70875421,
       0.70934343, 0.70875421, 0.70934343]), 'split2_test_score': array([0.68518519, 0.68602694, 0.68518519, 0.68602694, 0.6952862 ,
       0.69781145, 0.6952862 , 0.69781145]), 'split3_test_score': array([0.68930976, 0.69149832, 0.68930976, 0.69149832, 0.69856902,
       0.7010101 , 0.69856902, 0.7010101 ]), 'split4_test_score': array([0.68863636, 0.69031987, 0.68863636, 0.69031987, 0.70159933,
       0.7013468 , 0.70159933, 0.7013468 ]), 'mean_test_score': array([0.69097643, 0.69213805, 0.69097643, 0.69213805, 0.70281145,
       0.70430976, 0.70281145, 0.70430976]), 'std_test_score': array([0.00452871, 0.00428569, 0.00452871, 0.00428569, 0.00567333,
       0.00542114, 0.00567333, 0.00542114]), 'rank_test_score': array([7, 5, 7, 5, 3, 1, 3, 1], dtype=int32)}
{'mean_fit_time': array([32.2157577 , 63.10208287, 32.09989333, 63.37693086, 32.18453536,
       65.23128905, 31.99958458, 48.67857628]), 'std_fit_time': array([1.08532904, 1.85615037, 1.64955967, 2.16463864, 1.14473929,
       1.66249365, 0.79498927, 0.40988313]), 'mean_score_time': array([0.96149635, 1.5352242 , 1.03327737, 1.65765634, 0.97909412,
       1.76784368, 0.79000068, 0.98170309]), 'std_score_time': array([0.22339202, 0.31593809, 0.11989693, 0.18409569, 0.14048134,
       0.21880138, 0.13536362, 0.16629604]), 'param_model__algorithm': masked_array(data=['SAMME', 'SAMME', 'SAMME', 'SAMME', 'SAMME.R',
                   'SAMME.R', 'SAMME.R', 'SAMME.R'],
             mask=[False, False, False, False, False, False, False, False],
       fill_value='?',
            dtype=object), 'param_model__learning_rate': masked_array(data=[0.01, 0.01, 0.1, 0.1, 0.01, 0.01, 0.1, 0.1],
             mask=[False, False, False, False, False, False, False, False],
       fill_value='?',
            dtype=object), 'param_model__n_estimators': masked_array(data=[50, 100, 50, 100, 50, 100, 50, 100],
             mask=[False, False, False, False, False, False, False, False],
       fill_value='?',
            dtype=object), 'params': [{'model__algorithm': 'SAMME', 'model__learning_rate': 0.01, 'model__n_estimators': 50}, {'model__algorithm': 'SAMME', 'model__learning_rate': 0.01, 'model__n_estimators': 100}, {'model__algorithm': 'SAMME', 'model__learning_rate': 0.1, 'model__n_estimators': 50}, {'model__algorithm': 'SAMME', 'model__learning_rate': 0.1, 'model__n_estimators': 100}, {'model__algorithm': 'SAMME.R', 'model__learning_rate': 0.01, 'model__n_estimators': 50}, {'model__algorithm': 'SAMME.R', 'model__learning_rate': 0.01, 'model__n_estimators': 100}, {'model__algorithm': 'SAMME.R', 'model__learning_rate': 0.1, 'model__n_estimators': 50}, {'model__algorithm': 'SAMME.R', 'model__learning_rate': 0.1, 'model__n_estimators': 100}], 'split0_test_score': array([0.64208754, 0.64208754, 0.68998316, 0.69149832, 0.69856902,
       0.69856902, 0.70092593, 0.70530303]), 'split1_test_score': array([0.64604377, 0.64604377, 0.68872054, 0.69553872, 0.69638047,
       0.69638047, 0.69806397, 0.70176768]), 'split2_test_score': array([0.63880471, 0.63880471, 0.68148148, 0.68215488, 0.68686869,
       0.68686869, 0.68880471, 0.69494949]), 'split3_test_score': array([0.64132997, 0.64132997, 0.68594276, 0.68644781, 0.69124579,
       0.69124579, 0.69309764, 0.69848485]), 'split4_test_score': array([0.64335017, 0.64335017, 0.68535354, 0.68627946, 0.69377104,
       0.69377104, 0.69427609, 0.69772727]), 'mean_test_score': array([0.64232323, 0.64232323, 0.6862963 , 0.68838384, 0.693367  ,
       0.693367  , 0.69503367, 0.69964646]), 'std_test_score': array([0.00237988, 0.00237988, 0.0029552 , 0.00464476, 0.00407512,
       0.00407512, 0.00417189, 0.00356624]), 'rank_test_score': array([7, 7, 6, 5, 3, 3, 2, 1], dtype=int32)}

In [49]:
scoring_list[0].best_estimator_

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('cat',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(fill_value='missing',
                                                                                 strategy='constant')),
                                                                  ('encoder',
                                                                   OneHotEncoder(handle_unknown='ignore',
                                                                                 sparse=False))]),
                                                  ['basin', 'region',
                                                   'public_meeting',
                                                   'recorded_by',
                                                   'scheme_management',
                                                   'permit', 'extraction_type',
                                                   'management',
                                                   'management_group',
                                                   '...,
                                                   'water_quality', 'quantity',
                                                   'source',
                                                   'waterpoint_type']),
                                                 ('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['amount_tsh', 'gps_height',
                                                   'longitude', 'latitude',
                                                   'num_private', 'region_code',
                                                   'district_code',
                                                   'population',
                                                   'construction_year'])])),
                ('model',
                 RandomForestClassifier(max_depth=4, random_state=42))])

In [45]:
rfc_df = pd.DataFrame(scoring_list[0].cv_results_)

In [46]:
rfc_df.head()

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_model__max_depth,param_model__max_features,param_model__n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,5.045387,0.582568,0.385939,0.082421,3,auto,50,"{'model__max_depth': 3, 'model__max_features':...",0.693350,0.698401,0.685185,0.689310,0.688636,0.690976,0.004529,7
1,9.006215,0.388298,0.702843,0.093221,3,auto,100,"{'model__max_depth': 3, 'model__max_features':...",0.693771,0.699074,0.686027,0.691498,0.690320,0.692138,0.004286,5
2,5.474946,0.278208,0.309246,0.037507,3,sqrt,50,"{'model__max_depth': 3, 'model__max_features':...",0.693350,0.698401,0.685185,0.689310,0.688636,0.690976,0.004529,7
3,9.594718,0.796464,0.544061,0.097205,3,sqrt,100,"{'model__max_depth': 3, 'model__max_features':...",0.693771,0.699074,0.686027,0.691498,0.690320,0.692138,0.004286,5
4,6.158551,0.397865,0.385714,0.092967,4,auto,50,"{'model__max_depth': 4, 'model__max_features':...",0.709848,0.708754,0.695286,0.698569,0.701599,0.702811,0.005673,3

In [90]:
scoring_df = None
for i, model in enumerate(scoring_list):
    
    if i == 0:
        scoring_df = pd.DataFrame(scoring_list[i].cv_results_)
        scoring_df.insert(loc=0, column='algo', value=list(models.keys())[i])
        
    else:
        new_algo_data = pd.DataFrame(scoring_list[i].cv_results_)
        new_algo_data.insert(loc=0, column='algo', value=list(models.keys())[i])
        scoring_df = pd.concat([scoring_df, new_algo_data], axis=0)

In [89]:
scoring_df.sort_values(by='mean_test_score', ascending=False)[['algo', 'mean_test_score', 'params']]

  algo  mean_test_score                                             params
5  RFC         0.704310  {'model__max_depth': 4, 'model__max_features':...
7  RFC         0.704310  {'model__max_depth': 4, 'model__max_features':...
4  RFC         0.702811  {'model__max_depth': 4, 'model__max_features':...
6  RFC         0.702811  {'model__max_depth': 4, 'model__max_features':...
7  ADA         0.699646  {'model__algorithm': 'SAMME.R', 'model__learni...
6  ADA         0.695034  {'model__algorithm': 'SAMME.R', 'model__learni...
4  ADA         0.693367  {'model__algorithm': 'SAMME.R', 'model__learni...
5  ADA         0.693367  {'model__algorithm': 'SAMME.R', 'model__learni...
1  RFC         0.692138  {'model__max_depth': 3, 'model__max_features':...
3  RFC         0.692138  {'model__max_depth': 3, 'model__max_features':...
0  RFC         0.690976  {'model__max_depth': 3, 'model__max_features':...
2  RFC         0.690976  {'model__max_depth': 3, 'model__max_features':...
3  ADA         0.688384  {'model__algorithm': 'SAMME', 'model__learning...
2  ADA         0.686296  {'model__algorithm': 'SAMME', 'model__learning...
0  ADA         0.642323  {'model__algorithm': 'SAMME', 'model__learning...
1  ADA         0.642323  {'model__algorithm': 'SAMME', 'model__learning...

In [93]:
scoring_df

,algo,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_model__max_depth,param_model__max_features,param_model__n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score,param_model__algorithm,param_model__learning_rate
0,RFC,5.045387,0.582568,0.385939,0.082421,3,auto,50,"{'model__max_depth': 3, 'model__max_features':...",0.693350,0.698401,0.685185,0.689310,0.688636,0.690976,0.004529,7,NaN,NaN
1,RFC,9.006215,0.388298,0.702843,0.093221,3,auto,100,"{'model__max_depth': 3, 'model__max_features':...",0.693771,0.699074,0.686027,0.691498,0.690320,0.692138,0.004286,5,NaN,NaN
2,RFC,5.474946,0.278208,0.309246,0.037507,3,sqrt,50,"{'model__max_depth': 3, 'model__max_features':...",0.693350,0.698401,0.685185,0.689310,0.688636,0.690976,0.004529,7,NaN,NaN
3,RFC,9.594718,0.796464,0.544061,0.097205,3,sqrt,100,"{'model__max_depth': 3, 'model__max_features':...",0.693771,0.699074,0.686027,0.691498,0.690320,0.692138,0.004286,5,NaN,NaN
4,RFC,6.158551,0.397865,0.385714,0.092967,4,auto,50,"{'model__max_depth': 4, 'model__max_features':...",0.709848,0.708754,0.695286,0.698569,0.701599,0.702811,0.005673,3,NaN,NaN
5,RFC,11.037811,0.555155,0.518420,0.017555,4,auto,100,"{'model__max_depth': 4, 'model__max_features':...",0.712037,0.709343,0.697811,0.701010,0.701347,0.704310,0.005421,1,NaN,NaN
6,RFC,5.806404,0.502664,0.338114,0.074456,4,sqrt,50,"{'model__max_depth': 4, 'model__max_features':...",0.709848,0.708754,0.695286,0.698569,0.701599,0.702811,0.005673,3,NaN,NaN
7,RFC,8.123534,0.429289,0.263914,0.052550,4,sqrt,100,"{'model__max_depth': 4, 'model__max_features':...",0.712037,0.709343,0.697811,0.701010,0.701347,0.704310,0.005421,1,NaN,NaN
0,ADA,32.215758,1.085329,0.961496,0.223392,NaN,NaN,50,"{'model__algorithm': 'SAMME', 'model__learning...",0.642088,0.646044,0.638805,0.641330,0.643350,0.642323,0.002380,7,SAMME,0.01
1,ADA,63.102083,1.856150,1.535224,0.315938,NaN,NaN,100,"{'model__algorithm': 'SAMME', 'model__learning...",0.642088,0.646044,0.638805,0.641330,0.643350,0.642323,0.002380,7,SAMME,0.01
2,ADA,32.099893,1.649560,1.033277,0.119897,NaN,NaN,50,"{'model__algorithm': 'SAMME', 'model__learning...",0.689983,0.688721,0.681481,0.685943,0.685354,0.686296,0.002955,6,SAMME,0.1
3,ADA,63.376931,2.164639,1.657656,0.184096,NaN,NaN,100,"{'model__algorithm': 'SAMME', 'model__learning...",0.691498,0.695539,0.682155,0.686448,0.686279,0.688384,0.004645,5,SAMME,0.1
4,ADA,32.184535,1.144739,0.979094,0.140481,NaN,NaN,50,"{'model__algorithm': 'SAMME.R', 'model__learni...",0.698569,0.696380,0.686869,0.691246,0.693771,0.693367,0.004075,3,SAMME.R,0.01
5,ADA,65.231289,1.662494,1.767844,0.218801,NaN,NaN,100,"{'model__algorithm': 'SAMME.R', 'model__learni...",0.698569,0.696380,0.686869,0.691246,0.693771,0.693367,0.004075,3,SAMME.R,0.01
6,ADA,31.999585,0.794989,0.790001,0.135364,NaN,NaN,50,"{'model__algorithm': 'SAMME.R', 'model__learni...",0.700926,0.698064,0.688805,0.693098,0.694276,0.695034,0.004172,2,SAMME.R,0.1
7,ADA,48.678576,0.409883,0.981703,0.166296,NaN,NaN,100,"{'model__algorithm': 'SAMME.R', 'model__learni...",0.705303,0.701768,0.694949,0.698485,0.697727,0.699646,0.003566,1,SAMME.R,0.1